#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#------------------------------------------------------------------------------

restore0Dir

./Allrun-pre

runApplication blockMesh

runApplication setExprFields

runApplication $(getApplication)

#------------------------------------------------------------------------------